## Cluster
cluster.name: docker-cluster

## Node
node.name: ${NODE_NAME}

## Network
network.host: 0.0.0.0
network.publish_host: ${NODE_NAME}

## Discovery
discovery.seed_hosts: elasticsearch-master,elasticsearch-data-1,elasticsearch-data-2
cluster.initial_master_nodes: elasticsearch-master,elasticsearch-data-1,elasticsearch-data-2

## Security
xpack.security.enabled: true
xpack.security.enrollment.enabled: true

## X-Pack
xpack.license.self_generated.type: basic
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

## Bootstrap
bootstrap.memory_lock: false

## Gateway
gateway.recover_after_nodes: 1

## Various
action.auto_create_index: true

